package com.stschool.java.basics;

import java.util.Scanner;

public class DataVariable {
    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        System.out.println("enter age :");
        byte age = sc.nextByte();
        System.out.println(" enter charge percentage :");
        Byte chargePercentage = sc.nextByte();
        System.out.println("enter weeks :");
        Byte weeks = sc.nextByte();
        System.out.println("enter months :");
        Byte months = sc.nextByte();
        System.out.println("enter car wheels :");
        Byte carWheels = sc.nextByte();
        System.out.println("enter shirt price :");
        short shirtPrice = sc.nextShort();
        System.out.println("enter mobile cases price :");
        short mobileCasePrice = sc.nextShort();
        System.out.println("enter earphones price :");
        short earphonePrice = sc.nextShort();
        System.out.println("enter bag price");
        short bagPrice = sc.nextShort();
        System.out.println(" enter earmuffs price");
        short earMuffsPrice = sc.nextShort();
        System.out.println("enter moblie price");
        int mobilePrice = sc.nextInt();
        System.out.println("enter shoes price");
        int shoesPrice = sc.nextInt();
        System.out.println("enter house price");
        int housePrice = sc.nextInt();
        System.out.println("enter private jet price");
        int privateJetPrice = sc.nextInt();
        System.out.println("enter mobile number");
        long mobileNumber = sc.nextLong();
        System.out.println("enter pan id");
        long panId = sc.nextLong();
        System.out.println("aadhaar number");
        long aadhaarNumber = sc.nextLong();
        System.out.println("enter voterid");
        long voterId = sc.nextLong();
        System.out.println("enter temp");
        float temp = sc.nextFloat();
        System.out.println("enter rating");
        float rating = sc.nextFloat();
        System.out.println("enter percentage");
        float percentage = sc.nextFloat();
        System.out.println("enter cgpa");
        float cgpa = sc.nextFloat();
        System.out.println("enter height");
        float height = sc.nextFloat();
        System.out.println("enter price");
        double price = sc.nextDouble();
        System.out.println("enter salary");
        double salary = sc.nextDouble();
        System.out.println("enter wether forcast");
        double wetherForcast = sc.nextDouble();
        System.out.println("enter water density");
        double waterDensity = sc.nextDouble();
        System.out.println("Age : " + age);
        System.out.println("Charge percentage : " + chargePercentage );
        System.out.println(" Weeks : " +weeks );
        System.out.println("Months : " + months);
        System.out.println(" Car wheels : " + carWheels );
        System.out.println("Shirt price : " + shirtPrice);
        System.out.println("Mobile cases price : " + mobileCasePrice);
        System.out.println("Earphones price : " + earphonePrice);
        System.out.println("Bag price : " + bagPrice);
        System.out.println("Earmuffs price : " + earMuffsPrice);
        System.out.println("Mobile price : " + mobilePrice);
        System.out.println("Shoes price : " + shoesPrice);
        System.out.println("House price : " + housePrice);
        System.out.println("Private jet price : " + privateJetPrice);
        System.out.println("Mobile number : " + mobileNumber);
        System.out.println("Pan id : " + panId);
        System.out.println(" Aadhaar number : " + aadhaarNumber);
        System.out.println(" Voter id : " + voterId);
        System.out.println(" Temp : " + temp);
        System.out.println(" Rating : " + rating);
        System.out.println(" Percentage : " + percentage) ;
        System.out.println("Cgpa : " + cgpa);
        System.out.println("Height : " + height);
        System.out.println("Price : " + price);
        System.out.println("Salary : " + salary);
        System.out.println(" Weather forcast : " + wetherForcast);
        System.out.println(" Weather density : " + waterDensity);
        sc.close();
    }
}
